#!/bin/bash

source ./config

if [ ! -d "$VENV_DIR" ]; then
    echo "Virtual environment not found. Creating virtual environment..."
    python3 -m venv "$VENV_DIR"
else
    echo "Virtual environment already exists."
fi

# Activate the virtual environment
source "$VENV_DIR/bin/activate"

echo "Installing or updating dependencies..."
pip install -r requirements.txt

echo "Setup complete."
